### ISSUE TITLE
password-prompt@1.0.4  SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by Sathish-kumar-Subramani** [jdxcode/password-prompt#2]
/usr/lib/node_modules/sql-cli/node_modules/password-prompt/index.js:106
  )
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/lib/node_modules/sql-cli/lib/options.js:9:22

**Comment by anjsudh** [comment]
will fix this

**Comment by anjsudh** [comment]
https://github.com/jdxcode/password-prompt/pull/4

**Comment by matlev-qhr** [comment]
Following this issue, this is breaking our jenkins pipeline.

**Comment by ztotta** [comment]
same here, following as well

**Comment by RenBean** [comment]
Just installed this today and I have the same issue.
